language: objective-c
osx_image: xcode9.4

env:
    global:
        - WORKSPACE="NPOD Downloader.xcworkspace"
        - SCHEME="NPOD Downloader"
        - SDK=macosx10.13
        - DESTINATION="arch=x86_64"

before_install:
    - gem install xcpretty
    - gem install xcpretty-travis-formatter
    - gem clean
    - pod update
    - xcodebuild -version
    - xcodebuild -showsdks

script: xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug test | xcpretty -f `xcpretty-travis-formatter` && exit ${PIPESTATUS[0]}
