language: objective-c
osx_image: xcode8.2

env:
    global:
        - WORKSPACE="NPOD Downloader.xcworkspace"
        - SCHEME="NOPD Downloader"
        - SDK=macosx10.12
        - DESTINATION="arch=x86_64"

before_install:
    - brew update
    - brew upgrade
    - gem update
    - gem install xcpretty
    - gem install xcpretty-travis-formatter
    - gem clean
    - pod update
    - xcodebuild -version
    - xcodebuild -showsdks

script: xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug test
